name: example
description: Example project for the flutter_translate library
publish_to: none
version: 2.0.0

environment:
  sdk: ">=2.5.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_translate:
    path: ../

flutter:

  uses-material-design: true
  assets:
    - assets/i18n/
